<a href="https://colab.research.google.com/github/8dci/mini_project/blob/main/Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/Traffic Accident Statistics as of 1439 H.CSV')
df

,الشهر,حادث تلفيات,حادث اصابات,حادث وفيات,مجموع عدد الحوادث,السبت,الا حد,الاثنين,الثلاثاء,الا ربعاء,...,تجاوز غير نظامى,عدم التقيد بالاشارة,السرعة الزائدة,السائق تحت تأثير مخدر,اخرى.1,مجموع الحوادث حسب سبب الحادث,عدد المصابين,عدد المتوفين (القتلى),سليم,مجموع الأشخاص المشمولين بالحوادث
0,محرم,5047.0,277.0,75.0,5399.0,919.0,781.0,625.0,814.0,702.0,...,891.0,1208.0,1304.0,0.0,0.0,5399.0,393.0,100.0,12435.0,12928.0
1,صفر,5941.0,255.0,78.0,6274.0,1427.0,1407.0,1434.0,857.0,421.0,...,898.0,739.0,997.0,0.0,0.0,6274.0,433.0,98.0,9110.0,9641.0
2,ربيع أول,7808.0,271.0,87.0,8166.0,1209.0,1435.0,1121.0,1122.0,1140.0,...,1255.0,1380.0,2444.0,0.0,0.0,8166.0,455.0,105.0,15385.0,15945.0
3,ربيع ثانى,7821.0,266.0,79.0,8166.0,1368.0,1436.0,1094.0,1054.0,1085.0,...,1512.0,1366.0,1992.0,0.0,0.0,8166.0,427.0,91.0,15181.0,15699.0
4,جمادى أول,7923.0,237.0,81.0,8241.0,1410.0,1298.0,1014.0,1088.0,1110.0,...,1318.0,1426.0,2228.0,0.0,0.0,8241.0,358.0,96.0,15437.0,15891.0
5,جمادى ثانى,6449.0,259.0,79.0,6787.0,1015.0,1003.0,941.0,956.0,996.0,...,1187.0,1719.0,2091.0,0.0,0.0,6787.0,379.0,96.0,13404.0,13879.0
6,رجب,6955.0,227.0,65.0,7247.0,1164.0,1222.0,1015.0,1051.0,1023.0,...,1147.0,1165.0,1912.0,0.0,0.0,7247.0,383.0,83.0,14280.0,14746.0
7,شعبان,6516.0,258.0,63.0,6837.0,1162.0,970.0,1093.0,899.0,853.0,...,1813.0,896.0,2590.0,0.0,0.0,6837.0,393.0,75.0,14450.0,14918.0
8,رمضان,4997.0,229.0,71.0,5297.0,851.0,777.0,731.0,741.0,765.0,...,1078.0,988.0,1948.0,0.0,0.0,5297.0,335.0,82.0,12342.0,12759.0
9,شوال,5226.0,238.0,80.0,5544.0,755.0,633.0,783.0,833.0,840.0,...,1190.0,1143.0,1236.0,0.0,0.0,5544.0,384.0,100.0,9933.0,10417.0
10,ذى القعدة,5620.0,197.0,54.0,5871.0,923.0,852.0,912.0,849.0,847.0,...,1011.0,967.0,2134.0,0.0,300.0,5871.0,313.0,65.0,12267.0,12645.0
11,ذى الحجة,5786.0,183.0,86.0,6055.0,914.0,921.0,685.0,641.0,692.0,...,1501.0,947.0,2211.0,0.0,0.0,6055.0,301.0,100.0,13303.0,13704.0
12,المجموع,76089.0,2897.0,898.0,79884.0,13117.0,12735.0,11448.0,10905.0,10474.0,...,14801.0,13944.0,23087.0,0.0,300.0,79884.0,4554.0,1091.0,157527.0,163172.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 74 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   الشهر                                              13 non-null     object
 1   حادث تلفيات                                        13 non-null     float64
 2   حادث اصابات                                        13 non-null     float64
 3   حادث وفيات                                         13 non-null     float64
 4    مجموع عدد الحوادث                                 13 non-null     float64
 5   السبت                                              13 non-null     float64
 6   الا حد                                             13 non-null     float64
 7   الاثنين                                            13 non-null     float64
 8   الثلاثاء                                           13 non-null     float64
 9   الا ربعاء                                          13 non-null     float64
 10  الخميس                                             13 non-null     float64
 11  الجمعة                                             13 non-null     float64
 12  مجموع عدد الحوادث لجميع الأيام                     13 non-null     float64
 13  نهارا                                              13 non-null     float64
 14  ليلا                                               13 non-null     float64
 15  مجموع عدد الحوادث حسب الوقت                        13 non-null     float64
 16  داخل المدينة                                       13 non-null     float64
 17  خارج المدينة                                       13 non-null     float64
 18  مجموع عدد الحوادث حسب مكان الحادث                  13 non-null     float64
 19  صغيرة                                              13 non-null     float64
 20  جيب                                                13 non-null     float64
 21  حافلة                                              13 non-null     float64
 22  ونيت                                               13 non-null     float64
 23  نقل                                                13 non-null     float64
 24  وايت                                               13 non-null     float64
 25  اخرى                                               13 non-null     float64
 26  مجموع عدد السيارات المشتركة في الحوادث حسب الطراز  13 non-null     float64
 27  الشهر.1                                            13 non-null     object
 28  -18.0                                              13 non-null     float64
 29  18+                                                13 non-null     float64
 30  30+                                                13 non-null     float64
 31  40+                                                13 non-null     float64
 32  50+                                                13 non-null     float64
 33  المجموع حسب العمر                                  13 non-null     float64
 34  سعودي                                              13 non-null     float64
 35  اجنبي                                              13 non-null     float64
 36  المجموع حسب الجنسية                                13 non-null     float64
 37  متزوج                                              13 non-null     float64
 38  اعزب                                               13 non-null     float64
 39  المجموع حسب الحالة الاجتماعية                      13 non-null     float64
 40  متعلم                                              13 non-null     float64
 41  امى                                                13 non-null     float64
 42  المجموع حسب الحالة التعليمية                       13 non-null     float64
 43  نوع الرخصة خصوصى                                   13 non-null     float64
 44  نوع الرخصة عمومى                                   13 non-null     float64
 45  نوع الرخصة اليات                                   13 non-null     float64
 46  نوع الرخصة دراجة                                   13 non-null     float64
 47  السائق لا يحمل رخصة قيادة                          13 non-null     float64
 48  المجموع                                            13 non-null     float64
 49  السائق لا يحمل رخصة قيادة.1                        13 non-null     float64
 50  الرخصة سارية                                       13 non-null     float64
 51  الرخصة منتهية                                      13 non-null     float64
 52  المجموع.1                                          13 non-null     float64
 53  تصادم مع سيارة                                     13 non-null     float64
 54  تصادم مع جسم ثابت                                  13 non-null     float64
 55  دهس مشاة                                           13 non-null     float64
 56  دهس حيوان                                          13 non-null     float64
 57  حريق                                               13 non-null     float64
 58  انقلاب                                             13 non-null     float64
 59  خروج عن الطريق                                     13 non-null     float64
 60  أخرى                                               13 non-null     float64
 61  المجموع.2                                          13 non-null     float64
 62  توقف غير نظامى                                     13 non-null     float64
 63  دوران غير نظامى                                    13 non-null     float64
 64  تجاوز غير نظامى                                    13 non-null     float64
 65  عدم التقيد بالاشارة                                13 non-null     float64
 66  السرعة الزائدة                                     13 non-null     float64
 67  السائق تحت تأثير مخدر                              13 non-null     float64
 68  اخرى.1                                             13 non-null     float64
 69  مجموع الحوادث حسب سبب الحادث                       13 non-null     float64
 70  عدد المصابين                                       13 non-null     float64
 71  عدد المتوفين (القتلى)                              13 non-null     float64
 72  سليم                                               13 non-null     float64
 73  مجموع الأشخاص المشمولين بالحوادث                   13 non-null     float64
dtypes: float64(72), object(2)
memory usage: 7.6+ KB

In [6]:
df.isna().sum()

الشهر                               0
حادث تلفيات                         0
حادث اصابات                         0
حادث وفيات                          0
 مجموع عدد الحوادث                  0
                                   ..
مجموع الحوادث حسب سبب الحادث        0
عدد المصابين                        0
عدد المتوفين (القتلى)               0
سليم                                0
مجموع الأشخاص المشمولين بالحوادث    0
Length: 74, dtype: int64

In [7]:
df.duplicated().sum()

0